# Generated by Django 2.0 on 2017-12-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='risks.Field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('enum', 'enum')], default='text', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('name',)},
        ),
    ]
