# Generated by Django 2.0 on 2017-12-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20171206_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Field'),
        ),
    ]
