# Generated by Django 2.0 on 2017-12-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_auto_20171206_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='option',
            new_name='choice',
        ),
    ]
