# Generated by Django 2.0 on 2017-12-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0006_auto_20171206_2245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=set(),
        ),
    ]
